### ISSUE TITLE
Touch event xy always with y=0

### ISSUE THREAD

**Issue by ivivona** [tingbot/tide#11]
Using latest Tide and the following code:

```
import tingbot
from tingbot import *

screen.fill(color='blue')

@touch()
def on_touch(xy):
    screen.fill('black')
    screen.text('touch: ' + str(xy), color='white')

# run the app
tingbot.run()
```

**Comment by joerick** [comment]
Hi @ivivona, thanks for the report. This is a bug with the simulator. I've verified and filed a bug on that project: tingbot/tingbot-python#34

A quick workaround for now is to move the window slightly - this resets something and the touch works properly again.

**Comment by joerick** [comment]
@ivivona, just fixed this in tingbot-python. Thanks the sample code, it was useful to verify the fix!

It'll be in the next release of tingbot-python and tide-electron.
