### ISSUE TITLE
Tide for Windows

### ISSUE THREAD

**Issue by joerick** [tingbot/tide#4]
Now that the campaign has closed, we're looking to start work on the Windows version.

If you'd like to help us build this app, please add a comment below and we can discuss how to get started!

**Comment by joerick** [comment]
First question in my mind is what technology to use. I'm a Python and Objective-C developer, but I don't know much about Windows development. I'd love to hear options and opinions on technologies we can use. 

These are the priorities, as I see it:
- It should look and feel like a native app. 
- It should be distributed as one single package - any dependencies are bundled for a good first-run experience (download -> install -> start the app -> run 'hello world' should be the minimum no. of clicks)
- It should be fairly mainstream, so there's a reasonable pool of developers out there that can help us build it.

The app can be broken down into a few components, hopefully mirroring the mac app where some of the work is done by a Python script, ssh, and rsync.

**Comment by qooroo** [comment]
There are two viable options on Windows - [WPF](https://en.wikipedia.org/wiki/Windows_Presentation_Foundation) or [Electron](http://electron.atom.io/)

I think native-ness wouldn't be a problem on either, at least as far as the IDE portion is concerned. I'm not sure how the current emulator works - perhaps you can do a simple architecture diagram? A full list of features would be useful too, I guess an integrated debugger isn't in the plans for now :)

The deployment story is a bit more interesting. Distributing updates should be considered as well as download + install I think. WPF has [ClickOnce](https://en.wikipedia.org/wiki/ClickOnce) and Electron uses [Squirrel](https://github.com/Squirrel). From experience Clickonce is OK as long as you're on the happy path, but once you try to do something custom it's less easy.

Personally I have more experience in WPF and it's the more native option, but I think Electron should be the way to go:
- Proven apps (e.g. Visual Studio Code, Atom, Slack)
- HTML/Javascript, bigger contributer pool (WPF devs are generally enterprise-y and relatively do less OSS)
- Already has code editors written with it which are open source, so should get python syntax highlighting for free, maybe even some linting
- Linux compatibility - would be cool to write tingbot apps on a tingbot!

So I think the first step would be to list out the features and draw out the architecture of the current OS X app. Then we can explore equivalents / alternative options on Windows.

**Comment by joerick** [comment]
Thanks @qooroo, open to either at this stage... given the success of Electron for IDEs it seems like a good choice. 

Here’s how Tide works when run is pressed for the simulator:

```
┌──────────────────┐                                                           
│     Tide GUI     │──────────────────┐                                        
└──────────────────┘            saves │                                        
          │                           │                                        
     runs │                           │                                        
          ▼                           ▼                                        
┌──────────────────┐  runs  ┌──────────────────┐                               
│      tbtool      │───────▶│ .tingapp bundle  │                               
└──────────────────┘        └──────────────────┘                               
                                      │                                        
                                      │ imports                                
                                      ▼                                        
                            ┌──────────────────┐           ┌──────────────────┐
                            │  tingbot-python  │──────────▶│    Simulator     │
                            └──────────────────┘ displays  └──────────────────┘
```

tbtool is a python script, that works like this:

```
    Usage: tbtool simulate <app>
           tbtool run <app> <hostname>
           tbtool install <app> <hostname>
```

Running/installing on the Tingbot is slightly different, tbtool calls ssh and rsync to do the copy.

```
┌──────────────────┐                                                                       
│     Tide GUI     │─────────────────┐                     ╱──────────────────────────────╱
└──────────────────┘            saves│                    ╱                              ╱│
          │                          │                   ╱                              ╱ │
     runs │                          │                  ╱                              ╱  │
          ▼                          │                 ┌──────────────────────────────┐   │
┌──────────────────┐                 │                 │TINGBOT                       │   │
│      tbtool      │                 │                 │                              │   │
└──────────────────┘                 │                 │                              │   │
          │                          │                 │     ┌──────────────────┐     │   │
     runs │                          │                 │     │ .tingapp bundle  │     │   ╱
          ▼                          ▼                 │     └──────────────────┘     │  ╱ 
┌──────────────────┐       ┌──────────────────┐        │               ▲              │ ╱  
│      rsync       │◀──────│ .tingapp bundle  │        │               │              │╱   
└──────────────────┘       └──────────────────┘        └───────────────┼──────────────┘    
          │                                                            │                   
          │            ┌─────────────────────────────────────────┐     │                   
          └────────────┤         ssh tunnel (over WiFi)          ├─────┘                   
            copies     └─────────────────────────────────────────┘                         
```

Tingbot discovery is by Bonjour a.k.a. zeroconf. Worth checking libraries are available for this on Windows?

Perhaps I could do a screencast with a demo of the current Tide functionality to show how things work at the moment?

**Comment by joerick** [comment]
Step one to getting the simulator working would be to port [tingbot-python](https://github.com/tingbot/tingbot-python) to Windows. Then we can run tingbot apps from the command line.

This porting could happen in tandem with the initial IDE work.

**Comment by Rob4001** [comment]
Hey, 
I have been interested in getting a version of Tide working for Linux (bit of an OSXPhobe), So I started creating an app to emulate the features on the OSX version in Electron... https://github.com/Rob4001/TidePower
Currently I have it running with the ACE editor (same settings as tide) and i have gotten the proof pf concept for simulating on Linux.
I would love to help with porting Tide to Electron, then you would get an IDE that could be run on all 3 major Operating Systems.
I have also been looking into how to port tingbot-python to Non Tingbot Linux platforms.

**Comment by joerick** [comment]
Hi @Rob4001 ! Great to have you. Glad that we're all on the same wavelength with Electron! I think this is the best way to go now.

Rob that repo you posted looks like a great starting point. Shall we pull that in to github.com/tingbot/tide-electron and work from there?

Here's the video screencap of Tide features as promised! 

[![video](http://cl.ly/0y3X0N1e0L15/Image%202015-12-14%20at%208.00.49%20pm.png)](http://cl.ly/2q3E3m0i1t2Y)

**Comment by furbrain** [comment]
wxPython could be an option for tingbot-python. It provides native-style windows in both Windows and linux (available as packages for most major distros), and it is possible to distribute the Windows version as a single package. I'm happy to start working on a wx-enabled version of tingbot-python.

**Comment by furbrain** [comment]
Actually no. I'm a numpty - looks like you are already using pygame as a graphics library, just tested on my ubuntu system, seems to work but we don't get the tingbot surround for the main window, and I get an error saying I don't have a mouse. Should be fairly straightforward to make this work - I'll have a play this evening

**Comment by Rob4001** [comment]
@furbrain this would probably be better discussed on the tingbot-python repo but currently of you are running Linux it assumes you are running on an RPi with the tingbot module or there is an OSX version as wil. I have submitted a pull request to allow you to run on Windows but to get it working on non tingbot Linux I think we need to find a good way of determining if we are running on tingbot or not, so we can enable mouse etc... Simplest way to do this would to split ARM vs x86/64

**Comment by Rob4001** [comment]
@joerick Yup, I would be happy if we used my work as a starting point, I have been working a bit on it to improve functionality and added a wee TODO created from your screencast specs

**Comment by joerick** [comment]
@Rob4001 I've pushed your TidePower repo to https://github.com/tingbot/tide-electron and made you a collaborator on that. Could you continue work on that?

Further conversations should be on the tide-electron repo, so I'll close out this issue.
